pipeline:
  output_path: output/balanced_data # inference on changepoints data only
  device: cuda

dataset:
  input_path: data/balanced_data.csv
  

network:
  threshold_face: 0.6
  model_name: enet_b0_8_best_afew
  threshold_dying_track_len: 30
  threshold_iou_min_track: 0.4
  max_idx_frame_debug: null
  len_face_tracks: 30
  num_intervals: 2
  max_cp_found: 1
  use_audio_features: True
  use_visual_features: True
  min_face_size: 40
  max_idx_frame_debug: null
  visualize_debug_face_track: False