pipeline:
  output_path: output/full_data # inference on full data using visual and audio features
  device: cuda

dataset:
  input_path: data/full_data.csv
  

network:
  threshold_face: 0.6
  model_name: enet_b0_8_best_afew
  threshold_dying_track_len: 200
  threshold_iou_min_track: 0.4
  min_frame_per_second: 1 # skip frame info.
  max_idx_frame_debug: 2000
  len_face_tracks: 150 # Ex: fps = 25 --> only track faces with more than 25 * 5 (seconds) frames
  num_intervals: 2
  max_cp_found: 1
  # min_seconds_per_segment: 200
  iou_threshold: 0.8
  min_face_size: 50
  visualize_debug_face_track: True
  similarity_threshold: 0.8
  use_audio_features: False
  use_visual_features: True